Repository Team-Promesa/Promesa-Backend, pull requests merged in 2025-07, with the labels that each got.

#55 feat: 리뷰 작성, 삭제, 수정 기능 구현
  .github/workflows/build.yml
  build.gradle
  src/main/java/com/promesa/promesa/common/advice/GlobalExceptionHandler.java
  src/main/java/com/promesa/promesa/common/application/OAuth2Service.java
  src/main/java/com/promesa/promesa/common/config/SecurityConfig.java
  src/main/java/com/promesa/promesa/domain/artist/domain/Artist.java
  src/main/java/com/promesa/promesa/domain/category/domain/Category.java
  src/main/java/com/promesa/promesa/domain/item/dao/ItemRepository.java
  src/main/java/com/promesa/promesa/domain/item/domain/Item.java
  src/main/java/com/promesa/promesa/domain/item/exception/ItemErrorCode.java
  src/main/java/com/promesa/promesa/domain/item/exception/ItemNotFoundException.java
  src/main/java/com/promesa/promesa/domain/itemCategory/domain/ItemCategory.java
  src/main/java/com/promesa/promesa/domain/review/api/ReviewController.java
  src/main/java/com/promesa/promesa/domain/review/application/ReviewImageService.java
  src/main/java/com/promesa/promesa/domain/review/application/ReviewService.java
  src/main/java/com/promesa/promesa/domain/review/dao/ReviewRepository.java
  src/main/java/com/promesa/promesa/domain/review/domain/Review.java
  src/main/java/com/promesa/promesa/domain/review/domain/ReviewImage.java
  src/main/java/com/promesa/promesa/domain/review/dto/request/AddReviewRequest.java
  src/main/java/com/promesa/promesa/domain/review/dto/request/UpdateReviewRequest.java
  src/main/java/com/promesa/promesa/domain/review/dto/response/ReviewResponse.java
  src/main/java/com/promesa/promesa/domain/review/exception/ReviewAccessDeniedException.java
  src/main/java/com/promesa/promesa/domain/review/exception/ReviewDuplicateException.java
  src/main/java/com/promesa/promesa/domain/review/exception/ReviewErrorCode.java
  src/main/java/com/promesa/promesa/domain/review/exception/ReviewItemMismatchException.java
  src/main/java/com/promesa/promesa/domain/review/exception/ReviewNotFoundException.java
  src/main/java/com/promesa/promesa/domain/review/exception/ReviewUnauthorizedException.java
  src/main/resources/application-test.yml
  src/main/resources/data.sql
  src/test/java/com/promesa/promesa/PromesaApplicationTests.java
Labels: 🚀feature

#90 feat: 도커 이미지 정리 추가
  scripts/before_install.sh
Labels: 🚀feature

#85 feat: 리뷰 조회 기능 구현
  src/main/java/com/promesa/promesa/common/config/QueryDslConfig.java
  src/main/java/com/promesa/promesa/common/config/SecurityConfig.java
  src/main/java/com/promesa/promesa/domain/review/api/ReviewController.java
  src/main/java/com/promesa/promesa/domain/review/application/ReviewService.java
  src/main/java/com/promesa/promesa/domain/review/domain/Review.java
  src/main/java/com/promesa/promesa/domain/review/dto/response/ReviewQueryDto.java
  src/main/java/com/promesa/promesa/domain/review/dto/response/ReviewResponse.java
  src/main/java/com/promesa/promesa/domain/review/query/ReviewQueryRepository.java
  src/main/resources/data.sql
Labels: 🚀feature

#93 feat: 작가/작품 위시리스트 추가/취소/조회 api 구현
  src/main/java/com/promesa/promesa/common/config/SecurityConfig.java
  src/main/java/com/promesa/promesa/domain/artist/application/ArtistService.java
  src/main/java/com/promesa/promesa/domain/artist/domain/Artist.java
  src/main/java/com/promesa/promesa/domain/item/domain/Item.java
  src/main/java/com/promesa/promesa/domain/wish/api/WishController.java
  src/main/java/com/promesa/promesa/domain/wish/application/WishService.java
  src/main/java/com/promesa/promesa/domain/wish/dao/WishRepository.java
  src/main/java/com/promesa/promesa/domain/wish/domain/TargetType.java
  src/main/java/com/promesa/promesa/domain/wish/domain/Wish.java
  src/main/java/com/promesa/promesa/domain/wish/dto/WishResponse.java
  src/main/java/com/promesa/promesa/domain/wish/dto/WishToggleResponse.java
  src/main/java/com/promesa/promesa/domain/wish/exception/DuplicatedWishException.java
  src/main/java/com/promesa/promesa/domain/wish/exception/UnsupportedTargetTypeException.java
  src/main/java/com/promesa/promesa/domain/wish/exception/WishErrorCode.java
  src/main/java/com/promesa/promesa/security/dev/DevTokenController.java
  src/main/java/com/promesa/promesa/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/promesa/promesa/security/jwt/JwtTokenProvider.java
  src/main/java/com/promesa/promesa/security/jwt/JwtUtil.java
  src/main/java/com/promesa/promesa/security/jwt/exception/JwtErrorCode.java
  src/main/resources/data.sql
Labels: 🚀feature

#97 refactor: 로그인 API 파라미터 추가
  src/main/java/com/promesa/promesa/security/jwt/refresh/RefreshService.java
  src/main/java/com/promesa/promesa/security/oauth/OAuth2SuccessHandler.java
Labels: ♻️refactor

#94 feat: 상품 상세 조회 기능 구현
  src/main/java/com/promesa/promesa/domain/artist/application/ArtistService.java
  src/main/java/com/promesa/promesa/domain/artist/dto/ArtistProfile.java
  src/main/java/com/promesa/promesa/domain/artist/dto/ArtistResponse.java
  src/main/java/com/promesa/promesa/domain/artist/dto/ArtistWish.java
  src/main/java/com/promesa/promesa/domain/item/api/ItemController.java
  src/main/java/com/promesa/promesa/domain/item/application/ItemInfoService.java
  src/main/java/com/promesa/promesa/domain/item/dao/ItemRepository.java
  src/main/java/com/promesa/promesa/domain/item/domain/Item.java
  src/main/java/com/promesa/promesa/domain/item/dto/ItemDetail.java
  src/main/java/com/promesa/promesa/domain/item/dto/ItemResponse.java
  src/main/java/com/promesa/promesa/domain/item/dto/ItemSale.java
  src/main/java/com/promesa/promesa/domain/item/dto/ItemSummary.java
  src/main/java/com/promesa/promesa/domain/item/dto/ItemWish.java
  src/main/java/com/promesa/promesa/domain/wish/dao/WishRepository.java
  src/main/resources/data.sql
Labels: 🚀feature

#106 refactor: 리뷰 조회 응답에 시각 반환
  src/main/java/com/promesa/promesa/domain/review/domain/ReviewImage.java
  src/main/java/com/promesa/promesa/domain/review/dto/response/ReviewQueryDto.java
  src/main/java/com/promesa/promesa/domain/review/dto/response/ReviewResponse.java
  src/main/java/com/promesa/promesa/domain/review/query/ReviewQueryRepository.java
  src/main/resources/data.sql
Labels: ♻️refactor

#113 fix: item 조회 시 sort 미적용
  src/main/java/com/promesa/promesa/domain/item/query/ItemQueryRepository.java
Labels: 🐛bug

#120 feat: 배송지 조회/수정/추가/삭제 하기
  src/main/java/com/promesa/promesa/domain/member/domain/Member.java
  src/main/java/com/promesa/promesa/domain/order/api/OrderController.java
  src/main/java/com/promesa/promesa/domain/shippingAddress/api/ShippingAddressController.java
  src/main/java/com/promesa/promesa/domain/shippingAddress/application/ShippingAddressService.java
  src/main/java/com/promesa/promesa/domain/shippingAddress/dao/ShippingAddressRepository.java
  src/main/java/com/promesa/promesa/domain/shippingAddress/domain/ShippingAddress.java
  src/main/java/com/promesa/promesa/domain/shippingAddress/dto/request/AddressRequest.java
  src/main/java/com/promesa/promesa/domain/shippingAddress/dto/response/AddressResponse.java
  src/main/java/com/promesa/promesa/domain/shippingAddress/exception/ShippingAddressAlreadyExistsException.java
  src/main/java/com/promesa/promesa/domain/shippingAddress/exception/ShippingAddressErrorCode.java
  src/main/java/com/promesa/promesa/domain/shippingAddress/exception/ShippingAddressNotFoundException.java
Labels: 🚀feature

#133 refactor: 이미지 업로드 시 키 생성 로직 수정
  src/main/java/com/promesa/promesa/common/application/S3Service.java
  src/main/java/com/promesa/promesa/common/consts/ImageType.java
  src/main/java/com/promesa/promesa/common/consts/SubType.java
  src/main/java/com/promesa/promesa/common/dto/s3/PresignedUrlRequest.java
  src/main/java/com/promesa/promesa/domain/review/application/ReviewImageService.java
Labels: ♻️refactor

#136 refactor: ItemPreviewResponse에 saleStatus 추가
  src/main/java/com/promesa/promesa/domain/exhibition/application/ExhibitionService.java
  src/main/java/com/promesa/promesa/domain/home/dto/ItemPreviewResponse.java
  src/main/java/com/promesa/promesa/domain/item/application/ItemService.java
  src/main/java/com/promesa/promesa/domain/item/domain/Item.java
  src/main/java/com/promesa/promesa/domain/item/domain/SaleStatus.java
  src/main/java/com/promesa/promesa/domain/item/query/ItemQueryRepository.java
  src/main/resources/data.sql
Labels: ♻️refactor

#134 feat: 주문 생성하기 기능 구현
  src/main/java/com/promesa/promesa/domain/cartItem/dao/CartItemRepository.java
  src/main/java/com/promesa/promesa/domain/cartItem/domain/CartItem.java
  src/main/java/com/promesa/promesa/domain/cartItem/exception/CartItemErrorCode.java
  src/main/java/com/promesa/promesa/domain/cartItem/exception/CartItemNotFoundException.java
  src/main/java/com/promesa/promesa/domain/order/api/OrderController.java
  src/main/java/com/promesa/promesa/domain/order/application/OrderService.java
  src/main/java/com/promesa/promesa/domain/order/dao/OrderRepository.java
  src/main/java/com/promesa/promesa/domain/order/domain/Order.java
  src/main/java/com/promesa/promesa/domain/order/domain/OrderItem.java
  src/main/java/com/promesa/promesa/domain/order/domain/OrderStatus.java
  src/main/java/com/promesa/promesa/domain/order/dto/OrderItemRequest.java
  src/main/java/com/promesa/promesa/domain/order/dto/OrderRequest.java
  src/main/java/com/promesa/promesa/domain/order/dto/OrderResponse.java
  src/main/java/com/promesa/promesa/domain/order/exception/OrderErrorCode.java
  src/main/java/com/promesa/promesa/domain/order/exception/UnknownOrderTypeException.java
  src/main/resources/data.sql
Labels: 🚀feature

#142 feat: 검색 기능
  src/main/java/com/promesa/promesa/common/config/SecurityConfig.java
  src/main/java/com/promesa/promesa/domain/artist/api/ArtistController.java
  src/main/java/com/promesa/promesa/domain/artist/dao/ArtistRepository.java
  src/main/java/com/promesa/promesa/domain/exhibition/api/ExhibitionController.java
  src/main/java/com/promesa/promesa/domain/exhibition/application/ExhibitionService.java
  src/main/java/com/promesa/promesa/domain/home/api/HomeController.java
  src/main/java/com/promesa/promesa/domain/home/application/HomeService.java
  src/main/java/com/promesa/promesa/domain/home/dto/response/BrandInfoResponse.java
  src/main/java/com/promesa/promesa/domain/home/dto/response/ItemPreviewResponse.java
  src/main/java/com/promesa/promesa/domain/home/dto/response/SearchResponse.java
  src/main/java/com/promesa/promesa/domain/item/api/ItemController.java
  src/main/java/com/promesa/promesa/domain/item/application/ItemService.java
  src/main/java/com/promesa/promesa/domain/item/query/ItemQueryRepository.java
Labels: 🚀feature

#144 feat: 기획전 상태별 목록 조회
  src/main/java/com/promesa/promesa/PromesaApplication.java
  src/main/java/com/promesa/promesa/domain/artist/api/ArtistController.java
  src/main/java/com/promesa/promesa/domain/exhibition/api/ExhibitionController.java
  src/main/java/com/promesa/promesa/domain/exhibition/application/ExhibitionService.java
  src/main/java/com/promesa/promesa/domain/exhibition/application/ExhibitionStatusScheduler.java
  src/main/java/com/promesa/promesa/domain/exhibition/dao/ExhibitionRepository.java
  src/main/java/com/promesa/promesa/domain/exhibition/domain/Exhibition.java
  src/main/java/com/promesa/promesa/domain/exhibition/domain/ExhibitionStatus.java
  src/main/java/com/promesa/promesa/domain/exhibition/dto/response/ExhibitionResponse.java
  src/main/java/com/promesa/promesa/domain/exhibition/dto/response/ExhibitionSummary.java
  src/main/java/com/promesa/promesa/domain/exhibition/query/ExhibitionQueryRepository.java
  src/main/resources/data.sql
Labels: 🚀feature

#150 fix: application-prod.yml 파일 누락
  Dockerfile
  scripts/start_app.sh
Labels: 🐛bug

#163 refactor: 리뷰 조회 시 작성자 이름 추가
  src/main/java/com/promesa/promesa/domain/review/dto/response/ReviewQueryDto.java
  src/main/java/com/promesa/promesa/domain/review/dto/response/ReviewResponse.java
  src/main/java/com/promesa/promesa/domain/review/query/ReviewQueryRepository.java
Labels: ♻️refactor

#168 refactor: 작가 subname 추가
  src/main/java/com/promesa/promesa/domain/artist/domain/Artist.java
  src/main/java/com/promesa/promesa/domain/artist/dto/ArtistProfile.java
  src/main/resources/data.sql
Labels: ♻️refactor

#167 feat: 특정 전시 조회 기능
  src/main/java/com/promesa/promesa/domain/exhibition/api/ExhibitionController.java
  src/main/java/com/promesa/promesa/domain/exhibition/application/ExhibitionService.java
  src/main/java/com/promesa/promesa/domain/exhibition/domain/Exhibition.java
  src/main/java/com/promesa/promesa/domain/exhibition/dto/response/ExhibitionDetail.java
  src/main/java/com/promesa/promesa/domain/exhibition/dto/response/ExhibitionDetailResponse.java
  src/main/java/com/promesa/promesa/domain/exhibition/dto/response/ExhibitionSummary.java
  src/main/java/com/promesa/promesa/domain/exhibition/dto/response/ExhibitionSummaryResponse.java
  src/main/java/com/promesa/promesa/domain/exhibition/query/ExhibitionQueryRepository.java
  src/main/resources/data.sql
Labels: 🚀feature
